repos:
  - repo: local
    hooks:
      - id: runic-format
        name: Runic Julia Formatter
        entry: julia --project=@. -e 'using Runic; Runic.main(["--inplace", "src"])'
        language: system
        files: \.jl$
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
