name = "OpenStreetMapIOGeneration"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["MOVIRO"]
version = "0.1.0"

[deps]
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"

[compat]
ProtoBuf = "1.2.0"
